AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Lambda Function SAM Template"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldFunction
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./src/
      Timeout: 10
      MemorySize: 128
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue HelloWorldFunctionSG
        SubnetIds:
          - !ImportValue PrivateSubnet1a
          - !ImportValue PrivateSubnet1c
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaBasicExecutionRole

Outputs:
  HelloWorldFunction:
    Description: "HelloWorldFunction ARN"
    Value: !GetAtt HelloWorldFunction.Arn
